myMallPrj/myMallPrj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

myMallPrj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('shopping/', include('shopping.urls')), # 서버IP/shopping
    path('admin/', admin.site.urls), # 서버IP/admin
    path('', include('single_pages.urls')), # 서버IP/
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # 서버IP/media

shopping/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('update_prod/<int:pk>/', views.PostUpdate.as_view()),
    path('create_prod/', views.PostCreate.as_view()),
    path('category/<str:slug>', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('', views.PostList.as_view()),
]

single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [ # 서버IP/
    path('', views.landing), # 서버IP/
    path('about_me/', views.about_me), # 서버IP/about_me
    path('my_page/', views.my_page)
]

shopping/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shopping/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = MarkdownxField()
    price = models.IntegerField(default=0)

    head_image = models.ImageField(upload_to='shopping/images/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/shopping/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_user = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists() :
            return self.author.socialaccount_set.first().get_avatar_url()
        else :
            return f'https://doitdjango.com/avatar/id/420/79c3d17f098ae0df/svg/{self.author.email}/'

single_pages/models.py
from django.db import models

shopping/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

shopping/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CommentForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Post, Category

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST' :
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'price', 'content', 'head_image', 'category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            return response
        else:
            return redirect('/shopping/')

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'price', 'content', 'head_image', 'category']

    template_name = 'shopping/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author :
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        return context

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        return response

class PostList(ListView) :
    model = Post
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context
#    template_name = 'blog/post_list.html'

class PostDetail(DetailView) :
    model = Post

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context

class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q}({self.get_queryset().count()})'

        return context

def category_page(request, slug):
    if slug == 'no_category':
        category = '기타'
        post_list = Post.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(request, 'shopping/post_list.html',
                  {
                      'post_list' : post_list,
                      'categories' : Category.objects.all(),
                      'no_category_post_count' : Post.objects.filter(category=None).count(),
                      'category' : category
                  })

single_pages/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from shopping.models import Post, Comment


def landing(request):
    recent_posts = Post.objects.order_by('-pk')[:3]
    return render(request, 'single_pages/landing.html',
                  {'recent_posts' : recent_posts})

def about_me(request):
    return render(request, 'single_pages/about_me.html')

@login_required
def my_page(request):
    comments = Comment.objects.all()
    comments_list = comments.filter(comment_user=request.user.username) # 내가 쓴 댓글만
    page = request.GET.get('page')
    if page is None:
        page = 1
    else:
        page = int(page)
    paginator = Paginator(comments_list, 6)
    posts = paginator.get_page(page)
    return render(request, 'single_pages/mypage.html', {'comments_list' : comments_list, 'posts' : posts})

shopping/templates/shopping/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block head_title %}Doleule{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shopping/bootstrap/styles.css' %}" rel="stylesheet" type="text/css" media="screen">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        {% include 'shopping/navbar.html' %}
        <!-- Header-->
        <!-- 여기에 라디오 아이콘 들어가서 이미지 넘어가는 -->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">DOLEULE</h1>
                    <p class="lead fw-normal text-white-50">실바니안 패밀리 쇼핑몰</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container mt-3">
        <div class="row">
          <div class="col-md-8 col-lg-9" id="main-area">
                {% block main-area %}
                {% endblock %}
          </div>
                <div class="col-md-4 col-lg-3">
            <!-- Search widget-->
            <div class="card mb-4">
              <div class="card-header">
                  <i class="fas fa-search"></i>&nbsp; &nbsp;Search
              </div>
              <div class="card-body">
                  <div class="input-group">
                      <input class="form-control" type="text" id="search-input" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                      <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
                  </div>
              </div>
            </div>

          <!-- Categories widget-->
          <div class="card mb-4" id="categories-card">
              <div class="card-header">Categories</div>
              <div class="card-body">
                  <div class="row">
                      <div>
                          <ul>
                              {% for c in categories %}
                              <li><a href="{{c.get_absolute_url}}">{{c}} ({{c.post_set.count}})</a></li>
                              {% endfor %}
                              <li><a href="http://127.0.0.1:8000/shopping/category/no_category">기타 ({{no_category_post_count}})</a> </li>
                          </ul>
                      </div>
                  </div>
              </div>
              </div>
          </div>
            </div>
        </div>
        </section>

        <script>
        function searchPost() {
            let searchValue = document.getElementById('search-input').value.trim();
            if(searchValue.length > 1) {
                location.href = "/shopping/search/" + searchValue + "/";
            }
            else {
                alert('검색어(' + searchValue + ')가 너무 짧습니다.');
            }
        };
        document.getElementById('search-input').addEventListener('keyup',
                            function(event) {
                                if(event.key == 'Enter') { searchPost(); }
                            }
        )
        </script>

        <!-- Footer-->
        {% include 'shopping/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

shopping/templates/shopping/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block head_title %}Doleule{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shopping/bootstrap/styles.css' %}" rel="stylesheet" type="text/css" media="screen">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        {% include 'shopping/navbar.html' %}
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5" id="main-area">
                {% block main-area %}
                {% endblock %}
            </div>
        </section>
        <!-- Footer-->
        {% include 'shopping/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

shopping/templates/shopping/footer.html
<!-- Footer-->
        <footer class="py-3 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">서울시 강남구 압구정로 423 2층 Sylvanian Families </p>
                <p class="m-0 text-center text-white">T: 02) 1234 - 5678</p>
                <p class="m-0 text-center text-white">Copyright &copy; 덕성여자대학교 20190119 김지민 2021 인터넷프로그래밍</p>
            </div>
        </footer>

shopping/templates/shopping/navbar.html
{% load socialaccount %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Doleule</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="/about_me/">About</a></li>
                        <li class="nav-item dropdown" id="categories-nav">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="/shopping/">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for c in categories %}
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/shopping/category/{{c.slug}}/">{{c}}({{c.post_set.count}})</a></li>
                                {% endfor %}
                                <li><a class="dropdown-item" href="http://127.0.0.1:8000/shopping/category/no_category/">기타({{no_category_post_count}})</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/my_page/">My Page</a></li>
                    </ul>
                    <form class="d-flex">
                        <ul class="navbar-nav ml-auto">
                          {% if user.is_authenticated %}
                          <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" role="button" data-toggle="dropdown">
                                  {% if user.socialaccount_set.all.0.get_avatar_url %}
                                  <img class="rounded-circle" width="25px"
                                    src="{{user.socialaccount_set.all.0.get_avatar_url}}">
                                  {% else %}
                                  <img class="rounded-circle" width="25px"
                                       src="https://doitdjango.com/avatar/id/420/79c3d17f098ae0df/svg/{{user.email}}/">
                                  {{user.username}}
                                  {% endif %}
                              </a>
                              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                  <a role="button" class="btn btn-primary" href="/accounts/logout/">
                                    Log Out
                                  </a>
                              </div>
                          </li>
                          {% else %}
                          <li class="nav-item">
                          <a role="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loginModal">
                            Log In
                          </a>
                        </li>
                          {% endif %}
                        </ul>
                        <a role="button" class="btn btn-outline-dark">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </a>
                    </form>
                </div>
            </div>
        </nav>
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                href="{% provider_login_url 'google' %}">
                <i class="fab fa-google"></i>&nbsp; &nbsp; Log in with Google</a>
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/"><i class="far fa-envelope"></i>&nbsp; &nbsp;Log in with E-mail</a>
          </div>
          <div class="col-md-6">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup"><i class="far fa-envelope"></i>&nbsp; &nbsp;Sign with E-mail</a>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

shopping/templates/shopping/post_detail.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}
{% block main-area %}
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ post.head_image.url }}" alt="..." /></div>
                    <div class="col-md-6">
                        <div class="small mb-1">{{ post.hook_text }}</div>
                        <h1 class="display-5 fw-bolder">{{ post.title }}</h1>
                        {% if post.category %}
                            <span class="mt-3 mb-3 badge bg-secondary float-left">{{post.category}}</span>
                        {% else %}
                            <span class="mt-3 mb-3 badge bg-secondary float-left">기타</span>
                        {% endif %}
                        <div class="fs-5 mb-5">
                            <!-- Product price-->
                            <p class="fw-bold">{{ post.price }}원</p>
                        </div>
                        <p class="mb-5 lead">{{ post.get_content_markdown | safe }}</p>
                        <div class="d-flex">
                            <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                <i class="bi-cart-fill me-1"></i>
                                Add to cart
                            </button>
                        </div>
                    </div>
                </div>
                <br>

                <!-- Comments section-->
                    <h4 class="fw-bold">후기</h4>
                    <div class="mb-5" id="comment-area">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="POST" action="{{post.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ comment_form | crispy }}
                                    </div><br>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                {% else %}
                                <a role="button" class="btn btn-outline-dark" href="#"
                                data-bs-toggle="modal" data-bs-target="#loginModal">Log in and leave a comment</a>
                                {% endif %}
                                <!-- Single comment-->
                                {% if post.comment_set.exists %}
                                {% for comment in post.comment_set.all %}
                                <div class="d-flex" id="comment-{{comment.pk}}">
                                    <div class="flex-shrink-0">
                                        <img class="rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px"/>
                                    </div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{comment.author.username}} &nbsp;&nbsp;&nbsp;
                                            <small class="text-muted">{{comment.created_at}}</small></div>
                                        <p>{{comment.content | linebreaks}}</p>
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

{% endblock %}

shopping/templates/shopping/post_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Add Product
{% endblock %}
{% block main-area %}
    <h1>Create New Product</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
        <br>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{form.media}}
{% endblock %}

shopping/templates/shopping/post_list.html
{% extends 'shopping/base.html' %}
{% block main-area %}
        {% if user.is_authenticated %}
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-info btn-small float-right" href="/shopping/create_prod">
                    <i class="fas fa-pen"></i>New Post
                </a>
            {% endif %}
        {% endif %}
                    <h1>
                        {% if category %}
                            <span>{{ category }}</span>
                        {% endif %}
                    </h1>
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-3 justify-content-center">
                    {% if post_list.exists %}
                    {% for p in post_list %}
                    <div class="col mb-5" id="post-{{p.pk}}">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product images-->
                            <img class="card-img-top" src="{{ p.head_image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ p.title }}</h5>
                                    {% if p.category %}
                                        <span class="mt-3 mb-3 badge bg-secondary float-left">{{p.category}}</span>
                                    {% else %}
                                        <span class="mt-3 mb-3 badge bg-secondary float-left">기타</span>
                                    {% endif %}
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <p class="card-text">{{ p.get_content_markdown | truncatewords_html:5 | safe }}</p>
                                    <!-- Product price-->
                                    <p class="fw-bold">{{ p.price }}원</p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ p.get_absolute_url }}">View detail</a></div>
                            </div>
                            <div class="card-footer">
                                <div class="small text-muted">{{ p.hook_text }}</div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                        <h2>창고 재정비중! 더 멋진 모습으로 찾아 뵙겠습니다</h2>
                    {% endif %}
                </div>
            <!--Pagination-->
            {% if is_paginated %}
            <ul class="pagination justify-content-center my-4">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Newer</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}">Older</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#!">Older</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
{% endblock %}

shopping/templates/shopping/post_update_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Add Product
{% endblock %}
{% block main-area %}
    <h1>Edit Product</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
        <br>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{form.media}}
{% endblock %}